version = 0.1

[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true

[default.deploy.parameters]
stack_name = "loige-fm"
resolve_s3 = true
s3_prefix = "loige-fm"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
