name: Sam

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Cloud Formation Linter
      uses: scottbrenner/cfn-lint-action@v2
    - name: Testing with CFN Lint Command
      uses: scottbrenner/cfn-lint-action@v2
      with:
        command: cfn-lint -t ./template.yaml
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install Zig toolchain
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.12.0
    - name: Install Cargo Lambda
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with:
        repo: cargo-lambda/cargo-lambda
        tag: v1.0.1 
        platform: linux
        arch: x86_64
    - run: sam build
