name: Sam

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Cloud Formation Linter
      uses: scottbrenner/cfn-lint-action@v2
    - name: Testing with CFN Lint Command
      uses: scottbrenner/cfn-lint-action@v2
      with:
        command: cfn-lint -t ./template.yaml
    - uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    - run: sam build --use-container
